#!/bin/sh

filename="./README.md"
if [ $# -eq 1 ]
then
  filename="$1"
fi
output_filename="./${filename%.*}.html"


html_header="<!DOCTYPE html>
<html>
<head>
  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">
</head>
<body>"
html_footer="</body>
</html>"

markdown=`markdown --html4tags ./$filename`

echo "$html_header
$markdown
$html_footer" > $output_filename

# Open with default browser.
xdg-open $output_filename
