#!/bin/sh
git push heroku master && heroku run rake db:reset && heroku run rake db:migrate VERSION=0 && heroku run rake db:migrate && heroku run rake db:populate && echo "Server online at http://$(heroku apps).herokuapp.com"

