#!/bin/sh

if [ $# -ne 1 ]
then
  rails_env="development"
else
  rails_env="$1"
fi
env="RAILS_ENV=$rails_env"

rm -rf public/system

if [ "$rails_env" = "development" ]
then
  rm db/development.sqlite3
  rake db:migrate $env VERSION=0 --trace && rake db:migrate $env --trace && rake db:populate $env --trace
fi

if [ "$rails_env" = "production" ]
then
  rake db:reset $env VERSION=0 --trace
fi
